name: Firebase Hosting Deployment

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Check for build script
        id: check-build
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then
            echo "BUILD_SCRIPT_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "BUILD_SCRIPT_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Build application (if build script exists)
        if: steps.check-build.outputs.BUILD_SCRIPT_EXISTS == 'true'
        run: npm run build

      - name: Set up Firebase Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase
        env:
          PORT: ${{ secrets.PORT }}
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_ADMIN_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_ACCESS_TOKEN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          echo "📦 Environment variables set"
          echo "📁 Directory contents:"
          ls -la
          echo "🔥 Deploying to Firebase..."
          firebase deploy --only hosting --non-interactive
          echo "✅ Deployment completed!"
          echo "🌐 Your site is live at: https://jazmin-search-94c89.web.app"